#!/bin/sh

# update ports
portsnap fetch extract

# tvheadend user will need a login shell for maintenance
pw adduser \
	tvheadend \
	-d /usr/local/etc/tvheadend \
	-s /usr/local/bin/bash \
	-c "tvheadend"

# build tvheadend
cd /usr/ports/multimedia/tvheadend/ || exit 1
make -DBATCH depends

# configure build with portconf (doesn't work?)
# cat << 'EOF' > /usr/local/etc/ports.conf
# multimedia/tvheadend: WITH="DVBCSA, INOTIFY, TRANSCODING, XMLTV" | WITHOUT="AVAHI, DVBEN50221, HDHOMERUN"
# EOF

# configure build manually
mkdir -p /var/db/ports/multimedia_tvheadend
cat << 'EOF' > /var/db/ports/multimedia_tvheadend/options
# This file is auto-generated by 'make config'.
# Options for tvheadend-4.2.8_5
_OPTIONS_READ=tvheadend-4.2.8_5
_FILE_COMPLETE_OPTIONS_LIST=AVAHI DVBCSA DVBEN50221 HDHOMERUN INOTIFY TRANSCODING XMLTV
OPTIONS_FILE_UNSET+=AVAHI
OPTIONS_FILE_SET+=DVBCSA
OPTIONS_FILE_UNSET+=DVBEN50221
OPTIONS_FILE_UNSET+=HDHOMERUN
OPTIONS_FILE_SET+=INOTIFY
OPTIONS_FILE_SET+=TRANSCODING
OPTIONS_FILE_SET+=XMLTV
EOF

make -DBATCH install distclean

# set -C mode to enable config
sysrc tvheadend_flags="-C"

# start services
sysrc tvheadend_enable="YES"
service tvheadend restart

# we need the time to be correct for EPG to work
sysrc ntpd_enable="YES"
service ntpd restart
